packages:
  - "packages/*"
  - "examples/*"
  - "apps/*"

allowBuilds:
  "esbuild@0.28.2": true

overrides:
  "@ai-sdk/gateway": "4.0.62"
  "@ai-sdk/mcp": "2.0.36"
  "@ai-sdk/openai": "4.0.46"
  "@ai-sdk/provider-utils": "5.0.29"
  "@ai-sdk/react": "4.0.80"
  ai: "7.0.77"
