import { createHash } from "node:crypto";

export type ViraMachineAcquisitionOutcome = "selected" | "declined" | "challenge-required";
export interface ViraNetworkTrustEvidence { readonly version: "1"; readonly evidenceId: string; readonly issuerId: string; readonly subjectRef: string; readonly verifierId: string; readonly issuedAtEpochMs: number; readonly expiresAtEpochMs: number; readonly keyId: string; readonly attestationDigest: string; readonly result: "verified" | "rejected"; readonly revokedAtEpochMs: number | null }
export interface ViraExactCommercialOffer { readonly version: "1"; readonly offerRef: string; readonly sellerId: string; readonly providerId: string; readonly organizationId: string; readonly applicationRef: string; readonly capabilityRef: string | null; readonly bindingRef: string | null; readonly locationId: string | null; readonly planRef: string; readonly settlementRef: string; readonly currency: string; readonly amountNanos: string; readonly validFromEpochMs: number; readonly expiresAtEpochMs: number; readonly trustEvidenceId: string }
export interface ViraDelegatedCommercialMandate { readonly version: "1"; readonly mandateRef: string; readonly principalKind: "agent" | "service"; readonly principalId: string; readonly organizationId: string; readonly projectId: string; readonly environment: string; readonly applicationRef: string; readonly capabilityRef: string | null; readonly allowedSellerIds: readonly string[]; readonly allowedProviderIds: readonly string[]; readonly allowedCurrencies: readonly string[]; readonly perAcquisitionLimitNanos: string; readonly cumulativeLimitNanos: string; readonly spentNanos: string; readonly validFromEpochMs: number; readonly expiresAtEpochMs: number; readonly revokedAtEpochMs: number | null; readonly humanChallengeRequired: boolean }
export interface ViraExternalPaymentAuthorizationEvidence { readonly version: "1"; readonly evidenceRef: string; readonly adapterId: string; readonly providerId: string; readonly acquisitionId: string; readonly amountNanos: string; readonly currency: string; readonly outcome: "authorized" | "declined" | "challenge-required"; readonly expiresAtEpochMs: number }
export interface ViraMachineAcquisitionIntent { readonly version: "1"; readonly acquisitionId: string; readonly idempotencyKey: string; readonly organizationId: string; readonly projectId: string; readonly environment: string; readonly principalKind: "agent" | "service"; readonly principalId: string; readonly applicationRef: string; readonly capabilityRef: string | null; readonly offerRef: string; readonly mandateRef: string; readonly operationClass: "query" | "action"; readonly actionBoundaryEvidenceRef: string | null }
export interface ViraMachineAcquisitionDecision { readonly version: "1"; readonly outcome: ViraMachineAcquisitionOutcome; readonly acquisitionId: string; readonly offerRef: string; readonly mandateRef: string; readonly principalId: string; readonly amountNanos: string; readonly currency: string; readonly trustEvidenceId: string; readonly paymentAuthorizationEvidenceRef: string | null; readonly entitlementProvisioning: "eligible" | "forbidden"; readonly fundsMovement: "external-only"; readonly decisionDigest: string }
export interface ViraMachineCommerceReplayGuard { accept(input: { acquisitionId: string; idempotencyKey: string; organizationId: string }): boolean | Promise<boolean> }
export type ViraMachineCommerceResult = { readonly ok: true; readonly value: ViraMachineAcquisitionDecision } | { readonly ok: false; readonly issue: { readonly code: string; readonly path: string; readonly message: string } };

const REF = /^[A-Za-z0-9][A-Za-z0-9._:/@-]{0,255}$/;
const CURRENCY = /^[A-Z]{3}$/;
const DIGEST = /^sha256:[a-f0-9]{64}$/;
const MAX_NANOS = 9_223_372_036_854_775_807n;
function fail(code: string, path: string, message: string): ViraMachineCommerceResult { return { ok: false, issue: Object.freeze({ code, path, message }) }; }
function time(value: unknown): value is number { return Number.isSafeInteger(value) && (value as number) > 0; }
function nanos(value: string): bigint | null { if (!/^(0|[1-9][0-9]{0,18})$/.test(value)) return null; const parsed = BigInt(value); return parsed <= MAX_NANOS ? parsed : null; }
function uniqueBounded(values: readonly string[]): boolean { return values.length > 0 && values.length <= 64 && values.every((value) => REF.test(value)) && new Set(values).size === values.length; }
function exactKeys(value: unknown, keys: readonly string[]): boolean { if (value === null || typeof value !== "object" || Array.isArray(value)) return false; const actual = Object.keys(value).sort(); const expected = [...keys].sort(); return actual.length === expected.length && actual.every((key, index) => key === expected[index]); }

export function verifyViraNetworkTrustEvidence(evidence: ViraNetworkTrustEvidence, nowEpochMs: number): ViraMachineCommerceResult | { readonly ok: true; readonly value: ViraNetworkTrustEvidence } {
  if (!exactKeys(evidence, ["version", "evidenceId", "issuerId", "subjectRef", "verifierId", "issuedAtEpochMs", "expiresAtEpochMs", "keyId", "attestationDigest", "result", "revokedAtEpochMs"])) return fail("INVALID_TRUST_EVIDENCE", "$.trust", "trust evidence must be strict and versioned");
  if (evidence.version !== "1" || ![evidence.evidenceId, evidence.issuerId, evidence.subjectRef, evidence.verifierId, evidence.keyId].every((value) => REF.test(value)) || !DIGEST.test(evidence.attestationDigest) || !time(evidence.issuedAtEpochMs) || !time(evidence.expiresAtEpochMs) || !time(nowEpochMs) || evidence.issuedAtEpochMs > nowEpochMs) return fail("INVALID_TRUST_EVIDENCE", "$.trust", "trust evidence identity or time is invalid");
  if (evidence.result !== "verified") return fail("TRUST_REJECTED", "$.trust.result", "network trust was not verified");
  if (evidence.revokedAtEpochMs !== null && evidence.revokedAtEpochMs <= nowEpochMs) return fail("TRUST_REVOKED", "$.trust.revokedAtEpochMs", "network trust was revoked");
  if (evidence.expiresAtEpochMs <= nowEpochMs) return fail("TRUST_EXPIRED", "$.trust.expiresAtEpochMs", "network trust expired");
  return { ok: true, value: Object.freeze({ ...evidence }) };
}

export async function decideViraMachineAcquisition(input: { intent: ViraMachineAcquisitionIntent; offer: ViraExactCommercialOffer; mandate: ViraDelegatedCommercialMandate; trust: ViraNetworkTrustEvidence; payment: ViraExternalPaymentAuthorizationEvidence | null; nowEpochMs: number; replayGuard: ViraMachineCommerceReplayGuard }): Promise<ViraMachineCommerceResult> {
  const { intent, offer, mandate, trust, payment, nowEpochMs } = input;
  if (!intent || !offer || !mandate || !input.replayGuard || typeof input.replayGuard.accept !== "function" || !time(nowEpochMs)) return fail("INVALID_INPUT", "$", "machine acquisition input is invalid");
  if (!exactKeys(intent, ["version", "acquisitionId", "idempotencyKey", "organizationId", "projectId", "environment", "principalKind", "principalId", "applicationRef", "capabilityRef", "offerRef", "mandateRef", "operationClass", "actionBoundaryEvidenceRef"]) || intent.version !== "1" || ![intent.acquisitionId, intent.idempotencyKey, intent.organizationId, intent.projectId, intent.environment, intent.principalId, intent.applicationRef, intent.offerRef, intent.mandateRef].every((value) => REF.test(value)) || (intent.capabilityRef !== null && !REF.test(intent.capabilityRef))) return fail("INVALID_INPUT", "$.intent", "acquisition identity is invalid");
  if (!exactKeys(offer, ["version", "offerRef", "sellerId", "providerId", "organizationId", "applicationRef", "capabilityRef", "bindingRef", "locationId", "planRef", "settlementRef", "currency", "amountNanos", "validFromEpochMs", "expiresAtEpochMs", "trustEvidenceId"]) || offer.version !== "1" || ![offer.offerRef, offer.sellerId, offer.providerId, offer.organizationId, offer.applicationRef, offer.planRef, offer.settlementRef, offer.trustEvidenceId].every((value) => REF.test(value)) || [offer.capabilityRef, offer.bindingRef, offer.locationId].some((value) => value !== null && !REF.test(value)) || !CURRENCY.test(offer.currency) || nanos(offer.amountNanos) === null || !time(offer.validFromEpochMs) || !time(offer.expiresAtEpochMs) || offer.validFromEpochMs >= offer.expiresAtEpochMs) return fail("INVALID_OFFER", "$.offer", "commercial offer is not strict, bounded, and canonical");
  if (!exactKeys(mandate, ["version", "mandateRef", "principalKind", "principalId", "organizationId", "projectId", "environment", "applicationRef", "capabilityRef", "allowedSellerIds", "allowedProviderIds", "allowedCurrencies", "perAcquisitionLimitNanos", "cumulativeLimitNanos", "spentNanos", "validFromEpochMs", "expiresAtEpochMs", "revokedAtEpochMs", "humanChallengeRequired"]) || mandate.version !== "1" || ![mandate.mandateRef, mandate.principalId, mandate.organizationId, mandate.projectId, mandate.environment, mandate.applicationRef].every((value) => REF.test(value)) || (mandate.capabilityRef !== null && !REF.test(mandate.capabilityRef)) || !time(mandate.validFromEpochMs) || !time(mandate.expiresAtEpochMs) || mandate.validFromEpochMs >= mandate.expiresAtEpochMs || (mandate.revokedAtEpochMs !== null && !time(mandate.revokedAtEpochMs)) || typeof mandate.humanChallengeRequired !== "boolean") return fail("INVALID_MANDATE", "$.mandate", "commercial mandate is not strict, bounded, and canonical");
  if (payment !== null && (!exactKeys(payment, ["version", "evidenceRef", "adapterId", "providerId", "acquisitionId", "amountNanos", "currency", "outcome", "expiresAtEpochMs"]) || payment.version !== "1" || ![payment.evidenceRef, payment.adapterId, payment.providerId, payment.acquisitionId].every((value) => REF.test(value)) || nanos(payment.amountNanos) === null || !CURRENCY.test(payment.currency) || !time(payment.expiresAtEpochMs) || !["authorized", "declined", "challenge-required"].includes(payment.outcome))) return fail("INVALID_PAYMENT_EVIDENCE", "$.payment", "payment authorization evidence is invalid");
  const trusted = verifyViraNetworkTrustEvidence(trust, nowEpochMs); if (!trusted.ok) return trusted;
  if (trust.evidenceId !== offer.trustEvidenceId || trust.subjectRef !== offer.offerRef) return fail("TRUST_SUBJECT_MISMATCH", "$.trust.subjectRef", "trust evidence does not bind the exact offer");
  if (offer.offerRef !== intent.offerRef || mandate.mandateRef !== intent.mandateRef || offer.applicationRef !== intent.applicationRef || offer.capabilityRef !== intent.capabilityRef || mandate.applicationRef !== intent.applicationRef || mandate.capabilityRef !== intent.capabilityRef) return fail("EXACT_REFERENCE_MISMATCH", "$", "offer, mandate, and intent exact references drifted");
  if (intent.organizationId !== offer.organizationId || intent.organizationId !== mandate.organizationId || intent.projectId !== mandate.projectId || intent.environment !== mandate.environment) return fail("CROSS_ORGANIZATION", "$", "commercial evidence crossed tenant scope");
  if (intent.principalKind !== mandate.principalKind || intent.principalId !== mandate.principalId) return fail("PRINCIPAL_MISMATCH", "$.intent.principalId", "mandate does not bind the machine principal");
  if (offer.validFromEpochMs > nowEpochMs || offer.expiresAtEpochMs <= nowEpochMs) return fail("OFFER_EXPIRED", "$.offer.expiresAtEpochMs", "offer is not currently valid");
  if (mandate.revokedAtEpochMs !== null && mandate.revokedAtEpochMs <= nowEpochMs) return fail("MANDATE_REVOKED", "$.mandate.revokedAtEpochMs", "mandate was revoked");
  if (mandate.validFromEpochMs > nowEpochMs || mandate.expiresAtEpochMs <= nowEpochMs) return fail("MANDATE_EXPIRED", "$.mandate.expiresAtEpochMs", "mandate is not currently valid");
  if (!uniqueBounded(mandate.allowedSellerIds) || !uniqueBounded(mandate.allowedProviderIds) || mandate.allowedCurrencies.length < 1 || mandate.allowedCurrencies.length > 16 || new Set(mandate.allowedCurrencies).size !== mandate.allowedCurrencies.length || !mandate.allowedCurrencies.every((value) => CURRENCY.test(value))) return fail("INVALID_MANDATE", "$.mandate", "mandate allowlists are invalid");
  if (!mandate.allowedSellerIds.includes(offer.sellerId) || !mandate.allowedProviderIds.includes(offer.providerId) || !mandate.allowedCurrencies.includes(offer.currency)) return decision("declined", intent, offer, mandate, trust, payment, "forbidden");
  const amount = nanos(offer.amountNanos); const perLimit = nanos(mandate.perAcquisitionLimitNanos); const cumulative = nanos(mandate.cumulativeLimitNanos); const spent = nanos(mandate.spentNanos);
  if (amount === null || perLimit === null || cumulative === null || spent === null || amount > perLimit || spent > cumulative || amount > cumulative - spent) return fail("MANDATE_OVERFLOW", "$.offer.amountNanos", "acquisition exceeds bounded integer-nanos mandate");
  if (payment && payment.currency !== offer.currency) return fail("CURRENCY_MISMATCH", "$.payment.currency", "payment and offer currencies differ");
  if (intent.operationClass === "action" && (!intent.actionBoundaryEvidenceRef || !REF.test(intent.actionBoundaryEvidenceRef))) return fail("PROTECTED_ACTION_BYPASS", "$.intent.actionBoundaryEvidenceRef", "protected action requires Action Boundary evidence");
  let replayAccepted: boolean; try { replayAccepted = await input.replayGuard.accept({ acquisitionId: intent.acquisitionId, idempotencyKey: intent.idempotencyKey, organizationId: intent.organizationId }); } catch { return fail("REPLAY_GUARD_FAILED", "$.replayGuard", "replay guard failed closed"); }
  if (!replayAccepted) return fail("REPLAY_REJECTED", "$.intent.idempotencyKey", "acquisition replay was rejected");
  if (mandate.humanChallengeRequired || payment?.outcome === "challenge-required") return decision("challenge-required", intent, offer, mandate, trust, payment, "forbidden");
  if (!payment || payment.acquisitionId !== intent.acquisitionId || payment.amountNanos !== offer.amountNanos || payment.expiresAtEpochMs <= nowEpochMs) return fail("PAYMENT_EVIDENCE_MISMATCH", "$.payment", "external payment authorization does not bind the acquisition");
  if (payment.outcome === "declined") return decision("declined", intent, offer, mandate, trust, payment, "forbidden");
  return decision("selected", intent, offer, mandate, trust, payment, "eligible");
}

function decision(outcome: ViraMachineAcquisitionOutcome, intent: ViraMachineAcquisitionIntent, offer: ViraExactCommercialOffer, mandate: ViraDelegatedCommercialMandate, trust: ViraNetworkTrustEvidence, payment: ViraExternalPaymentAuthorizationEvidence | null, entitlementProvisioning: "eligible" | "forbidden"): ViraMachineCommerceResult {
  const evidence = { version: "1" as const, outcome, acquisitionId: intent.acquisitionId, offerRef: offer.offerRef, mandateRef: mandate.mandateRef, principalId: intent.principalId, amountNanos: offer.amountNanos, currency: offer.currency, trustEvidenceId: trust.evidenceId, paymentAuthorizationEvidenceRef: payment?.evidenceRef ?? null, entitlementProvisioning, fundsMovement: "external-only" as const };
  return { ok: true, value: Object.freeze({ ...evidence, decisionDigest: createHash("sha256").update(JSON.stringify(evidence)).digest("hex") }) };
}
