import { isSemanticNamespace, parseJsonValue } from "@vira-enterprise-genui/protocol";
import type { JsonObject, JsonValue } from "@vira-enterprise-genui/protocol";
import { createStudioComponentCatalog, validateStudioDocumentAgainstCatalog } from "@vira-enterprise-genui/studio-catalog";
import type { StudioCatalogPropType, StudioComponentCatalog } from "@vira-enterprise-genui/studio-catalog";
import { isStudioScopePath } from "@vira-enterprise-genui/studio-schema";
import type { StudioBinding, StudioBindingSource, StudioExperienceDocument, StudioInteractionPayloadBinding, StudioInteractionPayloadSource, StudioNode } from "@vira-enterprise-genui/studio-schema";
import { STUDIO_BINDING_LABEL_MAX_LENGTH, STUDIO_BINDING_MAX_SOURCES, STUDIO_BINDING_SOURCE_CATALOG_VERSION } from "./types.js";
import type { StudioActionPayloadTargetsResult, StudioBindingDocumentResult, StudioBindingSourceCatalog, StudioBindingSourceCatalogResult, StudioBindingSourceDefinition, StudioBindingTargetOption, StudioBindingTargetsResult, StudioBindingValidationCode, StudioBindingValueType, StudioRepeatTargetsResult } from "./types.js";

const sourceFields = new Set(["kind", "path", "label", "valueType"]);
const rootFields = new Set(["version", "id", "sources"]);
const valueTypes = new Set<StudioBindingValueType>(["string", "number", "boolean", "enum", "array", "object"]);
function failure(code: StudioBindingValidationCode, path: string, message: string): StudioBindingSourceCatalogResult { return { ok: false, issue: { code, path, message } }; }
function documentFailure(code: StudioBindingValidationCode, path: string, message: string): StudioBindingDocumentResult { return { ok: false, issue: { code, path, message } }; }
function targetFailure(code: StudioBindingValidationCode, path: string, message: string): StudioBindingTargetsResult { return { ok: false, issue: { code, path, message } }; }
function repeatFailure(code: StudioBindingValidationCode, path: string, message: string): StudioRepeatTargetsResult { return { ok: false, issue: { code, path, message } }; }
function payloadFailure(code: StudioBindingValidationCode, path: string, message: string): StudioActionPayloadTargetsResult { return { ok: false, issue: { code, path, message } }; }
function isObject(value: JsonValue | undefined): value is JsonObject { return value !== undefined && value !== null && typeof value === "object" && !Array.isArray(value); }
function freeze<T>(value: T): T { if (value === null || typeof value !== "object" || Object.isFrozen(value)) return value; if (Array.isArray(value)) { for (const item of value) freeze(item); return Object.freeze(value); } const record = value as Record<string, unknown>; for (const key of Object.keys(record)) freeze(record[key]); return Object.freeze(value); }
function validLabel(value: unknown): value is string { return typeof value === "string" && value.length > 0 && value.length <= STUDIO_BINDING_LABEL_MAX_LENGTH && value.trim() === value; }
function sourceKey(source: Pick<StudioBindingSourceDefinition, "kind" | "path">): string { return `${source.kind}:${source.path}`; }
function compatible(type: StudioCatalogPropType | StudioBindingValueType, source: StudioBindingSourceDefinition): boolean { return type === source.valueType; }
function nodeFor(document: StudioExperienceDocument, viewId: string, nodeId: string): StudioNode | undefined { return document.views.find((view) => view.id === viewId)?.nodes.find((node) => node.id === nodeId); }
function componentFor(catalog: StudioComponentCatalog, node: StudioNode | undefined) { return node ? catalog.components.find((component) => component.ref === node.component) : undefined; }
function inRepeatScope(document: StudioExperienceDocument, viewId: string, nodeId: string): boolean { const view = document.views.find((candidate) => candidate.id === viewId); if (!view) return false; const byId = new Map(view.nodes.map((node) => [node.id, node] as const)); let current = byId.get(nodeId); const seen = new Set<string>(); while (current && !seen.has(current.id)) { if (current.repeat) return true; seen.add(current.id); current = current.parentId ? byId.get(current.parentId) : undefined; } return false; }

export function createStudioBindingSourceCatalog(input: unknown): StudioBindingSourceCatalogResult {
  const parsed = parseJsonValue(input); if (!parsed.ok) return failure("INVALID_TYPE", parsed.issue.path, parsed.issue.reason); if (!isObject(parsed.value)) return failure("INVALID_TYPE", "$", "binding source catalog must be an object"); const fields = parsed.value;
  const unknown = Object.keys(fields).sort().find((field) => !rootFields.has(field)); if (unknown) return failure("UNKNOWN_FIELD", `$.${unknown}`, `unknown binding source catalog field: ${unknown}`);
  if (fields.version !== STUDIO_BINDING_SOURCE_CATALOG_VERSION) return failure("INVALID_VERSION", "$.version", `binding source catalog version must be ${STUDIO_BINDING_SOURCE_CATALOG_VERSION}`);
  if (typeof fields.id !== "string" || !isSemanticNamespace(fields.id)) return failure("INVALID_ID", "$.id", "binding source catalog id must be semantic");
  if (!Array.isArray(fields.sources)) return failure("INVALID_SOURCES", "$.sources", "sources must be an array"); if (fields.sources.length > STUDIO_BINDING_MAX_SOURCES) return failure("SOURCE_LIMIT_EXCEEDED", "$.sources", "source limit exceeded");
  const sources: StudioBindingSourceDefinition[] = []; const identities = new Set<string>();
  for (let index = 0; index < fields.sources.length; index += 1) { const raw = fields.sources[index]; const base = `$.sources[${index}]`; if (!isObject(raw)) return failure("INVALID_SOURCE", base, "source must be an object"); const extra = Object.keys(raw).sort().find((field) => !sourceFields.has(field)); if (extra) return failure("UNKNOWN_FIELD", `${base}.${extra}`, `unknown source field: ${extra}`);
    if (raw.kind !== "state" && raw.kind !== "domain" && raw.kind !== "scope") return failure("INVALID_SOURCE", `${base}.kind`, "source kind must be state, domain, or scope");
    if (typeof raw.path !== "string" || (raw.kind === "scope" ? !isStudioScopePath(raw.path) : !isSemanticNamespace(raw.path))) return failure("INVALID_SOURCE", `${base}.path`, raw.kind === "scope" ? "scope path must start with currentItem and use semantic tail segments" : "source path must be semantic");
    if (!validLabel(raw.label)) return failure("INVALID_LABEL", `${base}.label`, "source label must be a bounded trimmed string");
    if (typeof raw.valueType !== "string" || !valueTypes.has(raw.valueType as StudioBindingValueType)) return failure("INVALID_VALUE_TYPE", `${base}.valueType`, "unsupported binding value type");
    const normalized: StudioBindingSourceDefinition = { kind: raw.kind, path: raw.path, label: raw.label, valueType: raw.valueType as StudioBindingValueType }; const identity = sourceKey(normalized); if (identities.has(identity)) return failure("DUPLICATE_SOURCE", base, "duplicate source identity"); identities.add(identity); sources.push(normalized);
  }
  return { ok: true, value: freeze({ version: STUDIO_BINDING_SOURCE_CATALOG_VERSION, id: fields.id, sources }) };
}

function inputs(documentInput: unknown, catalogInput: unknown, sourcesInput: unknown): { readonly ok: true; readonly document: StudioExperienceDocument; readonly catalog: StudioComponentCatalog; readonly sources: StudioBindingSourceCatalog } | { readonly ok: false; readonly issue: { readonly code: StudioBindingValidationCode; readonly path: string; readonly message: string } } {
  const sources = createStudioBindingSourceCatalog(sourcesInput); if (!sources.ok) return sources;
  const catalog = createStudioComponentCatalog(catalogInput); if (!catalog.ok) return { ok: false, issue: { code: "INVALID_COMPONENT_CATALOG", path: `$.componentCatalog${catalog.issue.path.slice(1)}`, message: catalog.issue.message } };
  const document = validateStudioDocumentAgainstCatalog(documentInput, catalog.value); if (!document.ok) return { ok: false, issue: { code: "INVALID_DOCUMENT", path: `$.document${document.issue.path.slice(1)}`, message: document.issue.message } };
  return { ok: true, document: document.value, catalog: catalog.value, sources: sources.value };
}

export function validateStudioDocumentBindings(documentInput: unknown, componentCatalogInput: unknown, sourceCatalogInput: unknown): StudioBindingDocumentResult {
  const validated = inputs(documentInput, componentCatalogInput, sourceCatalogInput); if (!validated.ok) return { ok: false, issue: validated.issue }; const sourceMap = new Map(validated.sources.sources.map((source) => [sourceKey(source), source] as const));
  for (let index = 0; index < validated.document.bindings.length; index += 1) { const binding = validated.document.bindings[index]; if (!binding) continue; const source = sourceMap.get(sourceKey(binding.source)); if (!source) return documentFailure("UNREGISTERED_SOURCE", `$.document.bindings[${index}].source`, "binding source is not registered"); const node = nodeFor(validated.document, binding.viewId, binding.nodeId); const prop = componentFor(validated.catalog, node)?.props.find((candidate) => candidate.key === binding.prop); if (!node || !prop || !prop.bindable) return documentFailure("UNBINDABLE_PROP", `$.document.bindings[${index}].prop`, "binding target is not bindable"); if (!compatible(prop.type, source)) return documentFailure("INCOMPATIBLE_SOURCE", `$.document.bindings[${index}].source`, "binding source type is incompatible"); if (source.kind === "scope" && !inRepeatScope(validated.document, binding.viewId, binding.nodeId)) return documentFailure("SCOPE_OUTSIDE_REPEAT", `$.document.bindings[${index}].source`, "scope bindings are valid only on a repeated node or its descendants"); }
  for (let vi = 0; vi < validated.document.views.length; vi += 1) { const view = validated.document.views[vi]; if (!view) continue; for (let ni = 0; ni < view.nodes.length; ni += 1) { const node = view.nodes[ni]; if (!node?.repeat) continue; const source = sourceMap.get(sourceKey(node.repeat.source)); if (!source) return documentFailure("UNREGISTERED_SOURCE", `$.document.views[${vi}].nodes[${ni}].repeat.source`, "repeat source is not registered"); if (source.kind === "scope" || source.valueType !== "array") return documentFailure("INVALID_REPEAT_SOURCE", `$.document.views[${vi}].nodes[${ni}].repeat.source`, "repeat source must be a state/domain array source"); } }
  for (let ii = 0; ii < validated.document.interactions.length; ii += 1) { const interaction = validated.document.interactions[ii]; if (!interaction) continue; const node = nodeFor(validated.document, interaction.viewId, interaction.nodeId); const event = componentFor(validated.catalog, node)?.events.find((candidate) => candidate.name === interaction.event); for (let pi = 0; pi < (interaction.payloadBindings?.length ?? 0); pi += 1) { const payload = interaction.payloadBindings?.[pi]; if (!payload || payload.source.kind === "literal") continue; const source = sourceMap.get(sourceKey(payload.source)); if (!source) return documentFailure("UNREGISTERED_SOURCE", `$.document.interactions[${ii}].payloadBindings[${pi}].source`, "payload source is not registered"); const definition = event?.payload?.find((candidate) => candidate.key === payload.key); if (!definition || !compatible(definition.type, source)) return documentFailure("INCOMPATIBLE_SOURCE", `$.document.interactions[${ii}].payloadBindings[${pi}].source`, "payload source type is incompatible"); if (source.kind === "scope" && !inRepeatScope(validated.document, interaction.viewId, interaction.nodeId)) return documentFailure("SCOPE_OUTSIDE_REPEAT", `$.document.interactions[${ii}].payloadBindings[${pi}].source`, "scope payload binding is outside a repeat context"); } }
  return { ok: true, value: validated.document };
}

export function getStudioBindingTargets(documentInput: unknown, componentCatalogInput: unknown, sourceCatalogInput: unknown, viewId: string, nodeId: string): StudioBindingTargetsResult {
  const validated = validateStudioDocumentBindings(documentInput, componentCatalogInput, sourceCatalogInput); if (!validated.ok) return { ok: false, issue: validated.issue }; const catalog = createStudioComponentCatalog(componentCatalogInput); const sources = createStudioBindingSourceCatalog(sourceCatalogInput); if (!catalog.ok || !sources.ok) return targetFailure("INVALID_TYPE", "$", "validated inputs unavailable"); const node = nodeFor(validated.value, viewId, nodeId); const component = componentFor(catalog.value, node); if (!node || !component) return targetFailure("TARGET_NOT_FOUND", "$.nodeId", "node not found"); const current = new Map(validated.value.bindings.filter((binding) => binding.viewId === viewId && binding.nodeId === nodeId).map((binding) => [binding.prop, binding.source] as const)); const scoped = inRepeatScope(validated.value, viewId, nodeId);
  const targets: StudioBindingTargetOption[] = component.props.filter((prop) => prop.bindable).map((prop) => ({ prop: prop.key, valueType: prop.type, required: prop.required, compatibleSources: sources.value.sources.filter((source) => compatible(prop.type, source) && (source.kind !== "scope" || scoped)), ...(current.get(prop.key) ? { currentSource: current.get(prop.key) as StudioBindingSource } : {}) })); return { ok: true, value: freeze(targets) };
}

export function getStudioRepeatTargets(documentInput: unknown, componentCatalogInput: unknown, sourceCatalogInput: unknown, viewId: string, nodeId: string): StudioRepeatTargetsResult { const validated = validateStudioDocumentBindings(documentInput, componentCatalogInput, sourceCatalogInput); if (!validated.ok) return { ok: false, issue: validated.issue }; const sources = createStudioBindingSourceCatalog(sourceCatalogInput); if (!sources.ok) return { ok: false, issue: sources.issue }; const node = nodeFor(validated.value, viewId, nodeId); if (!node) return repeatFailure("TARGET_NOT_FOUND", "$.nodeId", "node not found"); return { ok: true, value: freeze({ compatibleSources: sources.value.sources.filter((source) => source.kind !== "scope" && source.valueType === "array"), ...(node.repeat ? { currentSource: node.repeat.source } : {}) }) }; }

export function getStudioActionPayloadTargets(documentInput: unknown, componentCatalogInput: unknown, sourceCatalogInput: unknown, viewId: string, nodeId: string, eventName: string): StudioActionPayloadTargetsResult { const validated = validateStudioDocumentBindings(documentInput, componentCatalogInput, sourceCatalogInput); if (!validated.ok) return { ok: false, issue: validated.issue }; const catalog = createStudioComponentCatalog(componentCatalogInput); const sources = createStudioBindingSourceCatalog(sourceCatalogInput); if (!catalog.ok || !sources.ok) return payloadFailure("INVALID_TYPE", "$", "validated inputs unavailable"); const node = nodeFor(validated.value, viewId, nodeId); const event = componentFor(catalog.value, node)?.events.find((candidate) => candidate.name === eventName); if (!node || !event) return payloadFailure("PAYLOAD_NOT_FOUND", "$.event", "component event not found"); const interaction = validated.value.interactions.find((candidate) => candidate.viewId === viewId && candidate.nodeId === nodeId && candidate.event === eventName); const current = new Map((interaction?.payloadBindings ?? []).map((binding) => [binding.key, binding.source] as const)); const scoped = inRepeatScope(validated.value, viewId, nodeId); return { ok: true, value: freeze((event.payload ?? []).map((definition) => ({ key: definition.key, valueType: definition.type, required: definition.required, compatibleSources: sources.value.sources.filter((source) => compatible(definition.type, source) && (source.kind !== "scope" || scoped)), ...(current.get(definition.key) ? { currentSource: current.get(definition.key) as StudioInteractionPayloadSource } : {}) }))) }; }

function replaceNode(document: StudioExperienceDocument, viewId: string, nodeId: string, mutate: (node: StudioNode) => StudioNode): StudioExperienceDocument { return { ...document, views: document.views.map((view) => view.id !== viewId ? view : { ...view, nodes: view.nodes.map((node) => node.id === nodeId ? mutate(node) : node) }) }; }
export function setStudioBinding(input: { readonly document: unknown; readonly componentCatalog: unknown; readonly sourceCatalog: unknown; readonly viewId: string; readonly nodeId: string; readonly prop: string; readonly source: StudioBindingSource }): StudioBindingDocumentResult { const validated = inputs(input.document, input.componentCatalog, input.sourceCatalog); if (!validated.ok) return { ok: false, issue: validated.issue }; const node = nodeFor(validated.document, input.viewId, input.nodeId); const prop = componentFor(validated.catalog, node)?.props.find((candidate) => candidate.key === input.prop); if (!node || !prop?.bindable) return documentFailure("UNBINDABLE_PROP", "$.prop", "target prop is not bindable"); const nextBindings: StudioBinding[] = validated.document.bindings.filter((binding) => !(binding.viewId === input.viewId && binding.nodeId === input.nodeId && binding.prop === input.prop)); nextBindings.push({ viewId: input.viewId, nodeId: input.nodeId, prop: input.prop, source: input.source }); const candidate = replaceNode({ ...validated.document, bindings: nextBindings }, input.viewId, input.nodeId, (target) => { const props = { ...target.props } as Record<string, JsonValue>; delete props[input.prop]; return { ...target, props }; }); return validateStudioDocumentBindings(candidate, validated.catalog, validated.sources); }
export function clearStudioBinding(input: { readonly document: unknown; readonly componentCatalog: unknown; readonly sourceCatalog: unknown; readonly viewId: string; readonly nodeId: string; readonly prop: string }): StudioBindingDocumentResult { const validated = inputs(input.document, input.componentCatalog, input.sourceCatalog); if (!validated.ok) return { ok: false, issue: validated.issue }; const node = nodeFor(validated.document, input.viewId, input.nodeId); const prop = componentFor(validated.catalog, node)?.props.find((candidate) => candidate.key === input.prop); if (!node || !prop?.bindable) return documentFailure("UNBINDABLE_PROP", "$.prop", "target prop is not bindable"); const hasBinding = validated.document.bindings.some((binding) => binding.viewId === input.viewId && binding.nodeId === input.nodeId && binding.prop === input.prop); if (hasBinding && prop.required && !Object.hasOwn(node.props, input.prop)) return documentFailure("REQUIRED_VALUE_MISSING", "$.prop", "clearing this binding would leave a required prop without a value"); const candidate = { ...validated.document, bindings: validated.document.bindings.filter((binding) => !(binding.viewId === input.viewId && binding.nodeId === input.nodeId && binding.prop === input.prop)) }; return validateStudioDocumentBindings(candidate, validated.catalog, validated.sources); }
export function setStudioRepeat(input: { readonly document: unknown; readonly componentCatalog: unknown; readonly sourceCatalog: unknown; readonly viewId: string; readonly nodeId: string; readonly source: StudioBindingSource }): StudioBindingDocumentResult { if (input.source.kind === "scope") return documentFailure("INVALID_REPEAT_SOURCE", "$.source", "repeat source cannot be scope"); const validated = inputs(input.document, input.componentCatalog, input.sourceCatalog); if (!validated.ok) return { ok: false, issue: validated.issue }; if (!nodeFor(validated.document, input.viewId, input.nodeId)) return documentFailure("TARGET_NOT_FOUND", "$.nodeId", "node not found"); const candidate = replaceNode(validated.document, input.viewId, input.nodeId, (node) => ({ ...node, repeat: { source: { kind: input.source.kind as "state" | "domain", path: input.source.path } } })); return validateStudioDocumentBindings(candidate, validated.catalog, validated.sources); }
export function clearStudioRepeat(input: { readonly document: unknown; readonly componentCatalog: unknown; readonly sourceCatalog: unknown; readonly viewId: string; readonly nodeId: string }): StudioBindingDocumentResult { const validated = inputs(input.document, input.componentCatalog, input.sourceCatalog); if (!validated.ok) return { ok: false, issue: validated.issue }; const candidate = replaceNode(validated.document, input.viewId, input.nodeId, (node) => { const rest = { ...node }; delete rest.repeat; return rest; }); return validateStudioDocumentBindings(candidate, validated.catalog, validated.sources); }
export function setStudioActionPayloadBinding(input: { readonly document: unknown; readonly componentCatalog: unknown; readonly sourceCatalog: unknown; readonly viewId: string; readonly nodeId: string; readonly event: string; readonly key: string; readonly source: StudioInteractionPayloadSource }): StudioBindingDocumentResult { const validated = inputs(input.document, input.componentCatalog, input.sourceCatalog); if (!validated.ok) return { ok: false, issue: validated.issue }; let found = false; const interactions = validated.document.interactions.map((interaction) => { if (interaction.viewId !== input.viewId || interaction.nodeId !== input.nodeId || interaction.event !== input.event) return interaction; found = true; const payloadBindings: StudioInteractionPayloadBinding[] = (interaction.payloadBindings ?? []).filter((binding) => binding.key !== input.key); payloadBindings.push({ key: input.key, source: input.source }); return { ...interaction, payloadBindings }; }); if (!found) return documentFailure("PAYLOAD_NOT_FOUND", "$.event", "action binding must exist before payload mapping"); return validateStudioDocumentBindings({ ...validated.document, interactions }, validated.catalog, validated.sources); }
export function clearStudioActionPayloadBinding(input: { readonly document: unknown; readonly componentCatalog: unknown; readonly sourceCatalog: unknown; readonly viewId: string; readonly nodeId: string; readonly event: string; readonly key: string }): StudioBindingDocumentResult { const validated = inputs(input.document, input.componentCatalog, input.sourceCatalog); if (!validated.ok) return { ok: false, issue: validated.issue }; const interactions = validated.document.interactions.map((interaction) => interaction.viewId !== input.viewId || interaction.nodeId !== input.nodeId || interaction.event !== input.event ? interaction : { ...interaction, payloadBindings: (interaction.payloadBindings ?? []).filter((binding) => binding.key !== input.key) }); return validateStudioDocumentBindings({ ...validated.document, interactions }, validated.catalog, validated.sources); }
