enum class ViraAndroidIssueCode {
  INVALID_ENVELOPE,
  INVALID_HOST,
  INVALID_PERMISSION_POLICY,
  INVALID_RUNTIME_STATE,
  INVALID_EVENT_PAYLOAD,
  DATA_VALUE_INVALID,
  STALE_SNAPSHOT,
  PERMISSION_DENIED,
  CONFIRMATION_REQUIRED,
  RUNTIME_REDUCTION_FAILED,
  RUNTIME_ACTION_UNHANDLED,
  REVISION_OVERFLOW,
  REPEAT_LIMIT_EXCEEDED,
  VIEW_NOT_FOUND,
  INTERACTION_NOT_FOUND,
  UNMAPPED_ACTION,
  ACTION_PENDING,
  SESSION_DISPOSED,
  DISPOSED,
}

data class ViraAndroidIssue(
  val code: ViraAndroidIssueCode,
  val path: String,
  val message: String,
) : Exception(message)
