import { createStudioComponentCatalog } from "@vira-enterprise-genui/studio-catalog";
import type { StudioCatalogComponentDefinition, StudioComponentCatalog } from "@vira-enterprise-genui/studio-catalog";
import { createStudioReactDesignState } from "@vira-enterprise-genui/studio-design-react";
import type { StudioRuntimeDispatchResult, StudioRuntimeNodeModel } from "@vira-enterprise-genui/studio-runtime";
import { Fragment, createElement } from "react";
import type { ReactNode } from "react";
import type { StudioRuntimeReactInput, StudioRuntimeReactRenderContext, StudioRuntimeReactRenderer, StudioRuntimeReactRenderResult, StudioRuntimeReactValidationCode } from "./types.js";
function failure(code: StudioRuntimeReactValidationCode, path: string, message: string): StudioRuntimeReactRenderResult { return { ok: false, issue: { code, path, message } }; }
type RegistryResult = { readonly ok: true; readonly value: ReadonlyMap<string, StudioRuntimeReactRenderer> } | { readonly ok: false; readonly result: StudioRuntimeReactRenderResult };
function readRendererRegistry(input: unknown, catalog: StudioComponentCatalog): RegistryResult {
  if (input === null || typeof input !== "object" || Array.isArray(input)) return { ok: false, result: failure("INVALID_RENDERER_REGISTRY", "$.renderers", "renderer registry must be a plain object") };
  const prototype = Object.getPrototypeOf(input); if (prototype !== Object.prototype && prototype !== null) return { ok: false, result: failure("INVALID_RENDERER_REGISTRY", "$.renderers", "renderer registry must be a plain object") };
  if (Object.getOwnPropertySymbols(input).length > 0 || Object.getOwnPropertyNames(input).length !== Object.keys(input).length) return { ok: false, result: failure("INVALID_RENDERER_REGISTRY", "$.renderers", "renderer registry must use enumerable string data properties only") };
  const expected = new Set(catalog.components.map((component) => component.ref)); const actual = Object.keys(input); const extra = actual.sort().find((key) => !expected.has(key)); if (extra) return { ok: false, result: failure("EXTRA_RENDERER", `$.renderers.${extra}`, "renderer registry contains a component not present in the active Studio catalog") };
  const output = new Map<string, StudioRuntimeReactRenderer>(); for (const ref of expected) { const descriptor = Object.getOwnPropertyDescriptor(input, ref); if (!descriptor || !("value" in descriptor)) return { ok: false, result: failure("MISSING_RENDERER", `$.renderers.${ref}`, "active Studio component is missing a trusted runtime renderer") }; if (typeof descriptor.value !== "function") return { ok: false, result: failure("INVALID_RENDERER_REGISTRY", `$.renderers.${ref}`, "runtime renderer must be a function") }; output.set(ref, descriptor.value as StudioRuntimeReactRenderer); }
  return { ok: true, value: output };
}
function deniedDispatch(nodeId: string, event: string): StudioRuntimeDispatchResult { return { ok: false, stage: "studio", issue: { code: "INTERACTION_NOT_FOUND", path: "$.event", message: `component event is not declared for ${nodeId}: ${event}` } }; }
export function renderStudioRuntimeReactView(input: StudioRuntimeReactInput): StudioRuntimeReactRenderResult {
  const catalog = createStudioComponentCatalog(input.componentCatalog); if (!catalog.ok) return failure("INVALID_CATALOG", `$.componentCatalog${catalog.issue.path.slice(1)}`, catalog.issue.message);
  const registry = readRendererRegistry(input.renderers, catalog.value); if (!registry.ok) return registry.result; const renderers = registry.value; const current = input.session.currentView(); if (!current.ok) return failure("VIEW_FAILED", current.issue.path, current.issue.message);
  const componentMap = new Map(catalog.value.components.map((component) => [component.ref, component] as const)); const nodeMap = new Map(current.value.nodes.map((node) => [node.id, node] as const)); const childMap = new Map<string, StudioRuntimeNodeModel[]>(); const roots: StudioRuntimeNodeModel[] = [];
  for (const node of current.value.nodes) { if (!componentMap.has(node.component)) return failure("UNREGISTERED_COMPONENT", `$.view.nodes.${node.id}.component`, "runtime view references a component outside the active Studio catalog"); if (node.parentId === undefined) { roots.push(node); continue; } const parent = nodeMap.get(node.parentId); if (!parent || node.slot === undefined) return failure("INVALID_SLOT_TARGET", `$.view.nodes.${node.id}`, "runtime view contains an invalid parent/slot relationship"); const parentComponent = componentMap.get(parent.component); if (!parentComponent?.slots.some((slot) => slot.name === node.slot)) return failure("INVALID_SLOT_TARGET", `$.view.nodes.${node.id}.slot`, "runtime child targets a slot not declared by its parent component"); const key = `${node.parentId}\u0000${node.slot}`; childMap.set(key, [...(childMap.get(key) ?? []), node]); }
  roots.sort((a, b) => a.order - b.order || a.id.localeCompare(b.id)); for (const children of childMap.values()) children.sort((a, b) => a.order - b.order || a.id.localeCompare(b.id));
  const active = new Set<string>(); const rendered = new Set<string>(); type NodeRenderResult = { readonly ok: true; readonly value: ReactNode } | { readonly ok: false; readonly result: StudioRuntimeReactRenderResult };
  function renderNode(node: StudioRuntimeNodeModel): NodeRenderResult {
    if (active.has(node.id) || rendered.has(node.id)) return { ok: false, result: failure("NODE_CYCLE", `$.view.nodes.${node.id}`, "runtime node is cyclic or reachable more than once") }; active.add(node.id);
    const component = componentMap.get(node.component) as StudioCatalogComponentDefinition; const renderer = renderers.get(node.component); if (!renderer) return { ok: false, result: failure("MISSING_RENDERER", `$.renderers.${node.component}`, "runtime renderer registry invariant failed") };
    const slots: Record<string, readonly ReactNode[]> = Object.create(null) as Record<string, readonly ReactNode[]>; for (const slot of component.slots) { const children = childMap.get(`${node.id}\u0000${slot.name}`) ?? []; const values: ReactNode[] = []; for (const child of children) { const value = renderNode(child); if (!value.ok) return value; values.push(value.value); } slots[slot.name] = Object.freeze(values); }
    const design = createStudioReactDesignState(node.props); const allowedEvents = new Set(component.events.map((event) => event.name)); const canonicalNodeId = node.sourceNodeId ?? node.id;
    const context: StudioRuntimeReactRenderContext = Object.freeze({ component: node.component, nodeId: canonicalNodeId, props: design.props, slots: Object.freeze(slots), emit: (event: string, payload?: unknown) => { if (!allowedEvents.has(event)) return deniedDispatch(canonicalNodeId, event); const external = payload !== null && typeof payload === "object" && !Array.isArray(payload) ? payload as Record<string, unknown> : {}; const mapped = node.eventPayloads?.[event] ?? {}; return input.session.dispatch({ nodeId: canonicalNodeId, event, payload: { ...external, ...mapped } }); } });
    let output: ReactNode; try { output = renderer(context); } catch { active.delete(node.id); return { ok: false, result: failure("RENDERER_FAILED", `$.renderers.${node.component}`, "trusted runtime renderer failed") }; }
    active.delete(node.id); rendered.add(node.id); return { ok: true, value: design.style === undefined ? createElement(Fragment, { key: node.id }, output) : createElement("div", { key: node.id, style: design.style }, output) };
  }
  const output: ReactNode[] = []; for (const root of roots) { const value = renderNode(root); if (!value.ok) return value.result; output.push(value.value); }
  if (rendered.size !== current.value.nodes.length) return failure("INVALID_SLOT_TARGET", "$.view.nodes", "runtime view contains nodes not reachable from a root component"); return { ok: true, value: createElement(Fragment, null, ...output) };
}
