import { createStudioReactDesignState } from "@vira-enterprise-genui/studio-design-react";
import type { StudioRuntimeNodeModel, StudioRuntimeSession } from "@vira-enterprise-genui/studio-runtime";
import { createElement } from "react";
import type { ReactElement, ReactNode } from "react";
import type { StudioRuntimeReactRenderer, StudioRuntimeReactRendererRegistry, StudioRuntimeReactRenderResult } from "./types.js";
function failure(path: string, message: string): StudioRuntimeReactRenderResult { return { ok: false, issue: { code: "RENDER_FAILED", path, message } }; }
function nodeKey(parentId: string | undefined, slot: string | undefined): string { return parentId === undefined ? "$root" : `${parentId}\u0000${slot ?? ""}`; }
export function renderStudioRuntimeReact(input: { readonly session: StudioRuntimeSession; readonly renderers: StudioRuntimeReactRendererRegistry }): StudioRuntimeReactRenderResult {
  const view = input.session.currentView(); if (!view.ok) return { ok: false, issue: { code: "RUNTIME_FAILED", path: view.issue.path, message: view.issue.message } }; const rendererMap = new Map<string, StudioRuntimeReactRenderer>(); for (const [key, value] of Object.entries(input.renderers)) { if (typeof value !== "function") return failure(`$.renderers.${key}`, "runtime renderer must be a function"); rendererMap.set(key, value); }
  const byScope = new Map<string, StudioRuntimeNodeModel[]>(); for (const node of view.value.nodes) { const key = nodeKey(node.parentId, node.slot); byScope.set(key, [...(byScope.get(key) ?? []), node]); } for (const nodes of byScope.values()) nodes.sort((a, b) => a.order - b.order);
  function renderNode(node: StudioRuntimeNodeModel): ReactNode { const renderer = rendererMap.get(node.component); if (!renderer) throw new Error(`Missing Studio runtime renderer: ${node.component}`); const slots: Record<string, ReactNode[]> = Object.create(null) as Record<string, ReactNode[]>; for (const [key, children] of byScope) { if (!key.startsWith(`${node.id}\u0000`)) continue; const slot = key.slice(node.id.length + 1); slots[slot] = children.map(renderNode); } const design = createStudioReactDesignState(node.props); const rendered = renderer({ component: node.component, nodeId: node.sourceNodeId, props: design.props, slots, emit: (event, payload) => { const mapped = node.eventPayloads[event] ?? {}; const external = payload !== null && typeof payload === "object" && !Array.isArray(payload) ? payload as Record<string, unknown> : {}; return input.session.dispatch({ nodeId: node.sourceNodeId, event, payload: { ...external, ...mapped } }); } }); return design.style === undefined ? rendered : createElement("div", { key: node.id, style: design.style }, rendered); }
  try { const roots = (byScope.get("$root") ?? []).map(renderNode); return { ok: true, value: createElement("div", { "data-vira-studio-runtime": view.value.experienceId }, ...roots) as ReactElement }; } catch (error) { return failure("$.render", error instanceof Error ? error.message : "Studio runtime React render failed"); }
}
