export const workspaceScope = "@vira-enterprise-genui/";

export const allowedDependencies = Object.freeze({
  protocol: [],
  "runtime-core": ["protocol"],
  planner: ["protocol", "runtime-core"],
  composer: ["protocol", "planner", "adapter-sdk"],
  "adapter-sdk": ["protocol"],
  "runtime-web": ["protocol", "runtime-core", "composer", "adapter-sdk", "security"],
  "web-component": ["runtime-web"],
  react: ["runtime-web"],
  security: [],
  telemetry: [],
  "tool-bridge": ["protocol"],
  "studio-schema": ["protocol"],
  "studio-compiler": ["studio-schema"],
  "studio-catalog": ["protocol", "studio-schema"],
  "studio-design": ["studio-schema", "studio-catalog"],
  "studio-design-react": ["studio-design"],
  "studio-puck-adapter": ["protocol", "studio-schema", "studio-catalog", "studio-design"],
  "studio-react": ["studio-schema", "studio-catalog", "studio-design-react", "studio-puck-adapter"],
  "studio-puck-authoring": ["protocol", "studio-schema", "studio-catalog", "studio-puck-adapter"],
  "studio-binding": ["protocol", "studio-schema", "studio-catalog"],
  "studio-flow": ["adapter-sdk", "studio-schema", "studio-catalog"],
  "studio-publish": ["studio-schema", "studio-compiler", "studio-binding", "studio-design", "studio-flow"],
  "studio-runtime": ["protocol", "runtime-web", "studio-schema", "studio-compiler", "studio-catalog", "studio-publish"],
  "studio-runtime-react": ["studio-catalog", "studio-design-react", "studio-runtime"],
  "studio-ai": ["protocol", "adapter-sdk", "studio-schema", "studio-catalog", "studio-binding", "studio-flow"],
});
