export const workspaceScope = "@vira-enterprise-genui/";

export const allowedDependencies = Object.freeze({
  protocol: [],
  "runtime-core": ["protocol"],
  "action-boundary": ["protocol", "runtime-core"],
  planner: ["protocol"],
  composer: ["protocol", "planner"],
  "adapter-sdk": ["protocol"],
  "experience-packs": [],
  "experience-registry": ["experience-packs"],
  "experience-resolver": ["protocol", "experience-packs", "experience-registry", "studio-host"],
  "experience-marketplace": ["experience-registry"],
  "design-system-compiler": ["studio-design"],
  "runtime-web": ["protocol", "runtime-core", "composer", "adapter-sdk", "security"],
  "web-component": ["runtime-web"],
  react: ["runtime-web"],
  security: [],
  "policy-engine": ["security"],
  telemetry: [],
  "experience-observability": ["telemetry"],
  "tool-bridge": ["protocol"],
  "protocol-gateway": ["tool-bridge"],
  "studio-schema": ["protocol"],
  "studio-compiler": ["studio-schema"],
  "studio-catalog": ["protocol", "studio-schema"],
  "studio-design": ["studio-schema", "studio-catalog"],
  "studio-design-react": ["studio-design"],
  "studio-puck-adapter": ["protocol", "studio-schema", "studio-catalog", "studio-design"],
  "studio-react": ["studio-schema", "studio-catalog", "studio-design-react", "studio-puck-adapter"],
  "studio-puck-authoring": ["protocol", "studio-schema", "studio-catalog", "studio-puck-adapter"],
  "studio-binding": ["protocol", "studio-schema", "studio-catalog"],
  "studio-flow": ["adapter-sdk", "studio-schema", "studio-catalog"],
  "studio-publish": ["studio-schema", "studio-compiler", "studio-binding", "studio-design", "studio-flow"],
  "studio-authoring": ["studio-enterprise", "studio-schema", "studio-publish"],
  "studio-runtime": ["protocol", "runtime-web", "studio-schema", "studio-compiler", "studio-catalog", "studio-publish"],
  "studio-runtime-react": ["studio-catalog", "studio-design-react", "studio-runtime"],
  "studio-ai": ["protocol", "adapter-sdk", "studio-schema", "studio-catalog", "studio-binding", "studio-flow"],
  "studio-workbench": ["adapter-sdk", "studio-schema", "studio-catalog", "studio-puck-authoring", "studio-binding", "studio-flow", "studio-publish"],
  "studio-workbench-react": ["studio-schema", "studio-compiler", "studio-react", "studio-binding", "studio-catalog", "studio-design", "studio-flow", "studio-workbench"],
  "studio-lifecycle": ["studio-schema", "studio-compiler", "studio-binding", "studio-design", "studio-flow", "studio-publish"],
  "studio-brand": ["protocol", "adapter-sdk", "design-system-compiler", "studio-schema", "studio-catalog", "studio-binding", "studio-flow"],
  "studio-brand-loader": ["protocol", "studio-brand", "studio-schema"],
  "studio-host": ["protocol"],
  "studio-host-runtime": ["studio-host", "studio-runtime", "studio-schema"],
  "studio-enterprise": ["protocol", "studio-schema"],
  genui: ["action-boundary", "experience-resolver", "protocol", "runtime-core", "studio-authoring", "studio-brand", "studio-host", "studio-host-runtime", "studio-publish", "studio-runtime", "studio-runtime-react"],
  "genui-cli": ["studio-authoring"],
  "genui-web-component": ["genui"],
});
