export const workspaceScope = "@vira-enterprise-genui/";

export const allowedDependencies = Object.freeze({
  protocol: [],
  "runtime-core": ["protocol"],
  "action-boundary": ["protocol", "runtime-core"],
  governance: ["action-boundary", "protocol", "runtime-core"],
  "enterprise-context": ["protocol"],
  "enterprise-governance": ["enterprise-context", "governance"],
  "enterprise-registry": ["enterprise-context", "experience-registry", "protocol"],
  "policy-simulation": ["protocol"],
  "deployment-plane": ["experience-packs", "protocol"],
  planner: ["protocol"],
  composer: ["protocol", "planner"],
  "adapter-sdk": ["protocol"],
  "application-package": ["protocol"],
  "application-distribution": ["application-package", "protocol"],
  "application-protocol-projection": ["application-distribution", "protocol"],
  "application-publisher-sdk": ["application-distribution", "application-package", "protocol"],
  "application-ai-host-sdk": ["application-distribution", "application-package", "protocol"],
  "capability-contract": ["protocol"],
  "work-context": ["protocol"],
  "application-graph": ["protocol"],
  "application-canvas": ["application-graph", "application-package", "protocol"],
  "application-canvas-ai": ["application-canvas", "application-package", "protocol"],
  "application-canvas-simulation": ["application-canvas", "protocol"],
  "application-canvas-collaboration": ["application-canvas", "protocol"],
  "application-canvas-design-import": ["application-canvas", "design-system-compiler", "protocol"],
  "experience-packs": [],
  "experience-pack-compositions": ["protocol", "studio-schema"],
  "experience-registry": ["experience-packs"],
  "experience-resolver": ["protocol", "experience-packs", "experience-registry", "studio-host"],
  "experience-marketplace": ["experience-registry"],
  "design-system-compiler": ["studio-design"],
  "runtime-web": ["protocol", "runtime-core", "composer", "adapter-sdk", "security"],
  "web-component": ["runtime-web"],
  react: ["runtime-web"],
  "external-brand-sdk": ["react"],
  security: [],
  "policy-engine": ["security"],
  telemetry: [],
  "experience-observability": ["telemetry"],
  "action-ledger": ["action-boundary", "experience-observability", "governance", "protocol", "runtime-core", "telemetry"],
  "cross-platform-conformance": ["action-boundary", "native-ux-gate", "protocol"],
  "native-ux-gate": [],
  "tool-bridge": ["protocol"],
  "protocol-gateway": ["protocol", "tool-bridge"],
  "studio-schema": ["protocol"],
  "studio-compiler": ["studio-schema"],
  "studio-catalog": ["protocol", "studio-schema"],
  "studio-design": ["studio-schema", "studio-catalog"],
  "studio-design-react": ["studio-design"],
  "studio-puck-adapter": ["protocol", "studio-schema", "studio-catalog", "studio-design"],
  "studio-react": ["studio-schema", "studio-catalog", "studio-design-react", "studio-puck-adapter"],
  "studio-puck-authoring": ["protocol", "studio-schema", "studio-catalog", "studio-puck-adapter"],
  "studio-binding": ["protocol", "studio-schema", "studio-catalog"],
  "studio-flow": ["adapter-sdk", "studio-schema", "studio-catalog"],
  "studio-publish": ["studio-schema", "studio-compiler", "studio-binding", "studio-design", "studio-flow"],
  "studio-authoring": ["studio-enterprise", "studio-schema", "studio-publish"],
  "studio-runtime": ["protocol", "runtime-web", "studio-schema", "studio-compiler", "studio-catalog", "studio-publish"],
  "studio-runtime-react": ["studio-catalog", "studio-design-react", "studio-runtime"],
  "studio-ai": ["protocol", "adapter-sdk", "studio-schema", "studio-catalog", "studio-binding", "studio-flow", "studio-brand", "studio-host"],
  "studio-workbench": ["adapter-sdk", "studio-schema", "studio-catalog", "studio-puck-authoring", "studio-binding", "studio-flow", "studio-publish"],
  "studio-workbench-react": ["studio-schema", "studio-compiler", "studio-react", "studio-binding", "studio-catalog", "studio-design", "studio-flow", "studio-workbench"],
  "studio-lifecycle": ["studio-schema", "studio-compiler", "studio-binding", "studio-design", "studio-flow", "studio-publish"],
  "studio-brand": ["protocol", "adapter-sdk", "design-system-compiler", "studio-schema", "studio-catalog", "studio-binding", "studio-flow"],
  "studio-brand-loader": ["protocol", "studio-brand", "studio-schema"],
  "studio-brand-console": ["enterprise-context", "protocol", "studio-brand", "studio-workbench"],
  "studio-host": ["protocol"],
  "studio-host-runtime": ["studio-host", "studio-runtime", "studio-schema"],
  "studio-enterprise": ["protocol", "studio-schema"],
  genui: ["action-boundary", "action-ledger", "cross-platform-conformance", "deployment-plane", "enterprise-context", "enterprise-governance", "enterprise-registry", "experience-pack-compositions", "governance", "native-ux-gate", "policy-simulation", "experience-resolver", "protocol", "runtime-core", "studio-ai", "studio-authoring", "studio-brand", "studio-brand-console", "studio-host", "studio-host-runtime", "studio-publish", "studio-runtime", "studio-runtime-react", "studio-workbench"],
  "genui-cli": ["studio-authoring"],
  "genui-web-component": ["genui"],
});
